# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 300)
        self.sortNameLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.sortNameLineEdit.setGeometry(QtCore.QRect(130, 20, 250, 20))
        self.sortNameLineEdit.setObjectName("sortNameLineEdit")
        self.roastLevelLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.roastLevelLineEdit.setGeometry(QtCore.QRect(130, 50, 250, 20))
        self.roastLevelLineEdit.setObjectName("roastLevelLineEdit")
        self.typeLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.typeLineEdit.setGeometry(QtCore.QRect(130, 80, 250, 20))
        self.typeLineEdit.setObjectName("typeLineEdit")
        self.flavorDescriptionTextEdit = QtWidgets.QTextEdit(AddEditCoffeeForm)
        self.flavorDescriptionTextEdit.setGeometry(QtCore.QRect(130, 110, 250, 50))
        self.flavorDescriptionTextEdit.setObjectName("flavorDescriptionTextEdit")
        self.priceLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.priceLineEdit.setGeometry(QtCore.QRect(130, 170, 250, 20))
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.packageVolumeLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.packageVolumeLineEdit.setGeometry(QtCore.QRect(130, 200, 250, 20))
        self.packageVolumeLineEdit.setObjectName("packageVolumeLineEdit")
        self.saveButton = QtWidgets.QPushButton(AddEditCoffeeForm)
        self.saveButton.setGeometry(QtCore.QRect(130, 240, 113, 32))
        self.saveButton.setObjectName("saveButton")
        self.cancelButton = QtWidgets.QPushButton(AddEditCoffeeForm)
        self.cancelButton.setGeometry(QtCore.QRect(250, 240, 113, 32))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Add/Edit Coffee"))
        self.sortNameLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Sort Name"))
        self.roastLevelLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Roast Level"))
        self.typeLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Type (Ground/Whole Bean)"))
        self.priceLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Price"))
        self.packageVolumeLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Package Volume"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Save"))
        self.cancelButton.setText(_translate("AddEditCoffeeForm", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddEditCoffeeForm = QtWidgets.QDialog()
    ui = Ui_AddEditCoffeeForm()
    ui.setupUi(AddEditCoffeeForm)
    AddEditCoffeeForm.show()
    sys.exit(app.exec_())
